# config.yaml

root_dir: '../hpde.io'
output_dir: './ODIS_JSONLD'
sitemap_file: './sitemap.xml'
base_url: "https://raw.githubusercontent.com/lechatpito/NASA-ODIS-Examples/main/"
datatypes:
  - DisplayData
skip_patterns:
  - deprecated
log_level: DEBUG


